In [1]:
import pandas as pd
import json

In [4]:
data=pd.read_excel("leave_data_v2.xlsx")

In [17]:
json_records=data.reset_index().to_json(orient='records')

In [20]:
json.loads(json_records,object_hook=datetime_parser)

NameError: name 'datetime_parser' is not defined

In [2]:
from datetime import datetime

In [4]:
today=datetime.today()

In [6]:
datetime.today()

datetime.datetime(2021, 1, 28, 12, 20, 11, 584701)

In [7]:
import datetime

In [9]:
today=datetime.date.today()

In [25]:
socm=today.replace(day=1)

In [19]:
sonm=socm.replace(day=28)+datetime.timedelta(days=4)

In [22]:
eocm=sonm-datetime.timedelta(days=sonm.day)

In [26]:
socm=socm.strftime('%d-%b-%Y')

In [27]:
eocm=eocm.strftime('%d-%b-%Y')

In [28]:
eocm

'31-Jan-2021'

In [29]:
from pandas.tseries.offsets import CustomBusinessDay

In [31]:
freq=CustomBusinessDay()

In [32]:
pd.DatetimeIndex(start=socm,end=eocm,freq=freq)

TypeError: __new__() got an unexpected keyword argument 'start'

In [42]:
pd.read_excel('leave_data_v2.xlsx',sheet_name=0)

,location,application,Resource_Analyst,2021-01-01 00:00:00,2021-01-04 00:00:00,2021-01-05 00:00:00,2021-01-06 00:00:00,2021-01-07 00:00:00,2021-01-08 00:00:00
0,Singapore,RDS/Scenarios/Myriad,"Dolas,Abhishek",EM,EM,EM,EM,EM,EM
1,Bangalore,RDS/Scenarios,"Kumari, Priyanka",A,A,A,A,A,A
2,Bangalore,TSRD,"Deka,Ushasee",H,H,H,H,H,H
3,Bangalore,RDS/Scenarios,"Bhoi, Hara Prasad",A,A,A,A,A,A
4,Bangalore,RDS/Scenarios,"Mittal, Pankaj",A,A,A,A,A,A
5,Singapore,MARS,"Dora, Subrat",M,M,M,M,M,M
6,Bangalore,MARS,"Mohapatra, Satyabrat",A,A,A,A,A,A
7,Bangalore,Monitoring,"Mujagond, Priyanka",M,M,M,M,M,M
8,Bangalore,RDS/Scenarios,"Mangalamadaka, Yaseswini",M,M,M,M,M,M
9,Bangalore,RDS/Scenarios,"Krishnappa, Lavanya",A,A,A,A,A,A
10,Bangalore,MARS,"Natarajan, Priyadharshini",M,M,M,M,M,M
11,Bangalore,MARS,"Nagaraj, Monica",A,A,A,A,A,A
12,Bangalore,Mars,"Padmanabhan, Revathi",A,A,A,A,A,A
13,Bangalore,Mars,"Kumar, Mohan",A,A,A,A,A,A
14,Bangalore,Monitoring,"Sampangula, Hemasree",A,A,A,A,A,A
15,Bangalore,Flex/PTA,"Pasha, Aasim",H,H,H,H,H,H
16,Bangalore,MRR,Gokul Paikar,A,A,A,A,A,A
17,Bangalore,Flex/PTA/TSRD,"Sainath Reddy, Bayagadda",G,G,G,G,G,G
18,Bangalore,Flex/PTA/TSRD,"Prabhu M, Vinayak",M,M,M,M,M,M
19,AMER,MARS/TSRD/FLEX/PTA,"Sharma, Gaurav",N,N,N,N,N,N
20,AMER,RDS/Scenarios,"Maithraye Ayyasamy, Raj",N,N,N,N,N,N
21,Pune,Myriad,"Mattas, Sapna",M,M,M,M,M,M
22,Pune,Myriad,"Gurbani, Hitesh",M,M,M,M,M,M
23,Pune,Myriad,"Kasukurthi, Kusumonika",A,A,A,A,A,A
24,Pune,Myriad,"Mukharjee, Sandeep",A,A,A,A,A,A
25,Pune,Myriad,"Dhiran, Dipali",A,A,A,A,A,A
26,Pune,Myriad,"Kumar, Hunny",A,A,A,A,A,A
27,AMER,Myriad,"Kulkarni, Abhijeet",N,N,N,N,N,N
28,Pune,Myriad,"Agrawal, Ashish",A,A,A,A,A,A
29,Pune,RFDAR,"Gour, Ajay",M,M,M,M,M,M
30,Pune,RFDAR,"Nagarkar, Prathamesh",M,M,M,M,M,M
31,Pune,RFDAR,"Azmatullah, Mohammed",M,M,M,M,M,M
32,Pune,RFDAR,"Kshirsagar, Kunika",M,M,M,M,M,M
33,Pune,RFDAR,"Borkar, Rohini V",M,M,M,M,M,M
34,Pune,RFDAR,"Shede, Sonali",M,M,M,M,M,M